[package]
name = "isis-trxvu"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]

[dependencies]
radio-api = { path = "../rust-radio-api" }
libc = "0.2"
nom = "4.0.0-beta1"
double = "0.2.2"

[build-dependencies]
kubos-build-helper = {path = "../../kubos-build-helper"}
