[package]
name = "mai400-service"
version = "0.1.0"
authors = ["Catherine Garabedian <catherine@kubos.co>"]

[dependencies]
i2c-linux = "0.1"
juniper =  "0.9"
serde_json = "1.0"
failure = { git = "https://github.com/rust-lang-nursery/failure" }
double = "0.2"
kubos-service = { git = "https://github.com/kubos/kubos", branch = "mai400-service" }
mai400-api = { git = "https://github.com/kubos/kubos", branch = "mai400-service" }

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.10"