[package]
name = "isis-ants-api"
version = "0.1.0"
authors = ["Catherine Garabedian <catherine@kubos.co>"]

[dependencies]
failure = { git = "https://github.com/rust-lang-nursery/failure" }


[build-dependencies]
kubos-build-helper = {path = "../../kubos-build-helper"}