sudo: required

language: c

env:
  global:
    - BUILD_DIR=/tmp/kubos-build
    - BASE_IMAGE=kubostech/build
    - IMAGE=kubostech/travis-build
  matrix:
    - TARGET=stm32f407-disco-gcc@openkosmosorg/target-stm32f407-disco-gcc#master TESTS=0

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python
  - mkdir $BUILD_DIR
  - git clone https://github.com/kyleparrott/kubos-rt-example $BUILD_DIR/kubos-rt-example
  - docker build -t $BASE_IMAGE $BUILD_DIR/kubos-rt-example/dist
  - docker build -t $IMAGE travis

script:
  - ./travis/build.sh
