sudo: required

language: c

env:
  global:
    - RIOTBASE=/tmp/kubos-build/RIOT
    - QUIET=0
  matrix:
    - BOARD=native TESTS=1
    - BOARD=stm32f4discovery TESTS=0

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python
  - mkdir /tmp/kubos-build
  - git clone -b kubos-master https://github.com/openkosmosorg/RIOT $RIOTBASE
  - docker build -t riotbuild $RIOTBASE/dist

script:
  - ./build/travis.sh
