[workspace]
members = [
"apis/adcs-api",
"apis/clyde-3g-eps-api",
"apis/eps-api",
"apis/isis-ants-api",
"apis/isis-imtq-api",
"apis/isis-iobc-supervisor",
"apis/nsl-duplex-d2",
"apis/rust-radio-api",
"examples/rust-service/extern-lib",
"examples/rust-service/service",
"hal/i2c-hal",
"kubos-build-helper",
"services/comms-service",
"services/iobc-supervisor-service",
"test/integration/linux/isis-ants",
]

[profile.release]
lto = true
