[workspace]
members = [
"apis/nsl-duplex-d2",
"apis/rust-radio-api",
"examples/rust-service/extern-lib",
"examples/rust-service/service",
"kubos-build-helper",
"hal/kubos-hal-iobc",
"services/comms-service",
"services/iobc-supervisor-service"
]
