[workspace]
members = [
"apis/isis-ants-api",
"apis/nsl-duplex-d2",
"apis/rust-radio-api",
"examples/rust-service/extern-lib",
"examples/rust-service/service",
"kubos-build-helper",
"services/comms-service",
"services/iobc-supervisor-service",
"services/isis-ants-service",
"test/integration/linux/isis-ants",
]
