[workspace]
members = [
"apis/adcs-api",
"apis/isis-ants-api",
"apis/isis-imtq-api",
"apis/isis-iobc-supervisor",
"apis/mai400-api",
"apis/mai400-api/examples/mai-test",
"apis/nsl-duplex-d2",
"apis/rust-radio-api",
"examples/rust-service/extern-lib",
"examples/rust-service/service",
"examples/udp-service-client",
"hal/rust-hal/rust-uart",
"kubos-build-helper",
"services/comms-service",
"services/kubos-service",
"services/iobc-supervisor-service",
"test/integration/linux/isis-ants",
]

[profile.release]
lto = true
opt-level = 3
opt-size = 2
panic = "abort"