[workspace]
members = [
"apis/isis-ants-api",
"apis/nsl-duplex-d2",
"apis/rust-radio-api",
"examples/rust-service/extern-lib",
"examples/rust-service/service",
"kubos-build-helper",
"services/comms-service",
"services/kubos-service",
"services/iobc-supervisor-service",
"test/integration/linux/isis-ants",
]

[profile.release]
lto = true
opt-level = 3
opt-size = 2
panic = "abort"