[package]
name = "isis-ants-service"
version = "0.1.0"
authors = ["Catherine Garabedian <catherine@kubos.co>"]

[dependencies]
juniper =  "0.9.2"
juniper_iron = "0.1.2"
iron = "0.6.0"
mount = "0.4.0"
logger = "0.4.0"

isis-ants-api = { path = "../../apis/isis-ants-api" }