version: 2
jobs:
    # Rust build + tests
    # Run for all PR commits
    rust:
      docker:
        - image: kubos/kubos-dev:latest
      steps:
        - checkout
        - run: ./tools/rustbuild.sh

    # CLI tests
    # Run for all PR commits
    cli_test:
      docker:
        - image: kubos/kubos-dev:latest
      steps:
        - checkout
        - run: python test/integration/integration_test.py
        - run: python -m tools.ci.lint
        - run: python tools/build.py --all-tests

    # C build + tests
    # Run for all PR commits
    c_test:
      docker:
        - image: kubos/kubos-dev:latest
      steps:
        - checkout
        - run: python tools/build.py --all-tests

    # Python tests
    # Run for all PR commits
    python_test:
      docker:
        - image: kubos/kubos-dev:latest
      steps:
        - checkout
        - run: python hal/python-hal/i2c/test_i2c.py
        - run: cd hal/python-hal/i2c; python setup.py install
        - run: cd apis/pumpkin-mcu-api; python test_mcu_api.py
        - run: cd apis/app-api/python; python test_app_api.py

    # Create and push new git version tag (n.n.n+{new build number})
    # Run when code is merged into master
    deploy:
      docker:
        - image: kubos/kubos-dev:latest
      steps:
        - checkout
        - run: pip install semantic-version
        - run: ./deploy.sh

    # Generate and upload new docs
    # Run when code is merged into master or when an official release tag is generated
    docs:
      docker:
        - image: kubos/kubos-dev:latest
      steps:
        - checkout
        - run: ssh-keyscan docs.kubos.co >> ~/.ssh/known_hosts
        - run: pip install semantic-version
        - run: ./prep_docs.sh
        - run: ./deploy_docs.sh

workflows:
  version: 2
  build:
    jobs:
      - rust:
          filters:
            branches:
              ignore: master
      - cli_test:
          filters:
            branches:
              ignore: master
      - c_test:
          filters:
            branches:
              ignore: master
      - python_test:
          filters:
            branches:
              ignore: master

  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
      - docs:
          requires:
            - deploy
  release:
    jobs:
      - docs:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
