[package]
name = "file-service-rust"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]

[dependencies]
simplelog = "^0.5.0"
log = "^0.4.0"
cbor-protocol = { path = "../../libs/cbor-protocol" }
file-protocol = { path = "../../libs/file-protocol" }
kubos-system = { path = "../../apis/system-api" }

[dev-dependencies]
rand = "0.5.5"
tempfile = "3"