[package]
name = "serial-comms-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.com>"]

[dependencies]
comms-service = { path = "../../libs/comms-service" }
failure = "0.1.3"
kubos-system = { path = "../../apis/system-api" }
log = "^0.4.0"
rust-uart = { path = "../../hal/rust-hal/rust-uart" }
syslog = "4.0"
serial = "0.4"
simplelog = "^0.5.0"
