[package]
name = "kubos-app"
version = "0.1.0"
authors = ["Marshall Culpepper <marshall@kubos.com>", "Catherine Garabedian <catherine@kubos.com>"]

[dependencies]
failure = { git = "https://github.com/rust-lang-nursery/failure", version = "1.0"  }
getopts = "0.2"
serde_json = "1.0"