[package]
name = "clyde-3g-eps-api"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]

[dependencies]
bitflags = "1.0"
failure = { git = "https://github.com/rust-lang-nursery/failure" }
i2c-api = { path = "../i2c-api" }