[package]
name = "nsl-duplex-d2"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]

[dependencies]
chrono = "0.4"
radio-api = { path = "../rust-radio-api" }
serde = "1.0"
serde_derive = "1.0.27"
serde_json = "1.0.9"
serial = "0.4"
nums_as_bytes = { path = "../../nums_as_bytes" }

[lib]
name = "duplex_d2_radio"
path = "src/duplex_d2.rs"
