[package]
name = "rust-hardware-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]

[dependencies]
extern-lib = { path = "../extern-lib" }
serde = "1.0"
serde_json = "1.0"
tokio = "0.1"
futures = "0.1"

[dependencies.juniper]
version = "0.9.2"