[pumpkin-mcu-service]

[pumpkin-mcu-service.modules]
[pumpkin-mcu-service.modules.sim]
address = 80
[pumpkin-mcu-service.modules.gpsrm]
address = 81
[pumpkin-mcu-service.modules.pim]
address = 83
[pumpkin-mcu-service.modules.rhm]
address = 85

[pumpkin-mcu-service.addr]
ip = "0.0.0.0"
port = 8101