[package]
name = "isis_imtq_api"
version = "0.1.0"
authors = ["Catherine Garabedian <catherine@kubos.co", "Ryan Plauche <ryan@kubos.co>"]

[dependencies]
failure = { git = "https://github.com/rust-lang-nursery/failure" }

[dev-dependencies]
double = "0.2.2"

[build-dependencies]
kubos-build-helper = {path = "../../kubos-build-helper"}
