[package]
name = "kubos-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
juniper = "0.9"
kubos-system = { path = "../../apis/system-api" }
log = "^0.4.0"

[dev-dependencies]
failure = "0.1.2"
