[app-service]
registry-dir = "app-registry"

[app-service.addr]
ip = "127.0.0.1"
port = 8000

[telemetry-service]
database = "telemetry.db"
direct_port = 8051

[telemetry-service.addr]
ip = "127.0.0.1"
port = 8050

[file-transfer-service]
storage_dir = "file-storage"
downlink_ip = "127.0.0.1"
downlink_port = 8080

[file-transfer-service.addr]
ip = "127.0.0.1"
port = 8070

[monitor-service.addr]
ip = "127.0.0.1"
port = 8030

[shell-service.addr]
ip = "127.0.0.1"
port = 8060