[package]
name = "rust-mission-app"
version = "0.1.0"
authors = ["Catherine Garabedian <catherine@kubos.co>"]

[dependencies]
chrono = "0.4"
getopts = "0.2"
kubos-app = { path = "../../apis/app-api/rust" }